### PR TITLE
added payout distro flag, combined controller set/migrate through dir…

### PR DESCRIPTION
**Pull request by mejango**
…ectory

# Description

- Add ruleset flag to ensurePrivilegedPayoutDistribution. A project can set this flag if it prefers the restrict the actions of distributing payouts to the project owner or an operator. Otherwise, anyone in the public can send this transaction.

This flag is useful to ensure the chance to send payouts with flashbot protection. It was brought to my attention from Haz here, though it's also been a lingering request over time with a palpable economic incentive:
image

In order to make space for this flag, I've combined Controller setting and migration. The project owner needs only to call the setController function in the Directory, which will in turn call the Migrate function of the controller. This also covers the audit finding from M-02:
image

## Limitations & risks

*Are there any trade-off or new vulnarbility surface based on theses changes?*

# Check-list
- [ ] Tests are covering the new feature
- [ ] Code is [natspec'd](https://docs.soliditylang.org/en/v0.8.17/natspec-format.html)
- [ ] Code is [linted and formatted](https://docs.soliditylang.org/en/v0.8.17/style-guide.html)
- [ ] I have run the test locally (and they pass)
- [ ] I have rebased to the latest main commit (and tests still pass)

# Interactions
These changes will impact the following contracts:
- Directly:

- Indirectly:

### CODE REVIEW

**Comment by chinmay-farkya** [comment]
M-02 has been fixed. Now there is only flow for setting a controller.

**Review by filipviz — CHANGES_REQUESTED** [review]
I think we should call the flag `ownerMustSendPayouts` instead of `ensurePrivilegedPayoutDistribution`.

How does that sound to you?

**Comment by simplemachine92** [comment]
LGTM ill adjust tests soon.

**Review by xBA5ED — APPROVED** [review]
I like!

**Pull request merged**
